repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-byte-order-marker
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-toml
      - id: debug-statements
      - id: name-tests-test
        args: [--django]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
